import math

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 640
SCREEN_TITLE = "Ray tracing"
MIDDLE_WIDTH = SCREEN_WIDTH / 2
MIDDLE_HEIGHT = SCREEN_HEIGHT / 2
WALLS_COUNT = 7
DEGREES = 360
RAYS_COUNT = math.floor(360 * 2.04)
RAY_LENGTH = SCREEN_WIDTH
PRINT_FOR = 0
